### ISSUE TITLE
Encoding problem in 'make acs-extraction'

### ISSUE THREAD

**Issue by mikeshulman** [active-calculus/active-calculus-single-mbx#225]
On current master, `make acs-extraction` fails for me (Red Hat linux) with the following error:

```
Traceback (most recent call last):
  File "/home/shulman/mathbook/script/mbx", line 1244, in <module>
    webwork_to_xml(xslt_executable, mbx_xsl_dir, args.xml_file, args.server, output_dir)
  File "/home/shulman/mathbook/script/mbx", line 549, in webwork_to_xml
    raise ValueError(msg.format(include_file_name) + root_cause)
ValueError: There was a problem writing a problem to the file: /home/shulman/active/output/webwork-extraction/webwork-extraction.xml
'ascii' codec can't encode character u'\x85' in position 2657: ordinal not in range(128)
```

**Comment by mitchkeller** [comment]
Have you pulled `mathbook` lately? If your `mathbook` is current, then I'll need your Python version to try to track things down, because macOS with python 3.5.1 works just fine for me.

**Comment by mikeshulman** [comment]
mathbook was not current, that did it.  Sorry for the noise.
